baseURL = "https://mature-sec.com"
languageCode = "zh-cn"
title = "Mature的博客 | 信安爱好者,专注于网络攻防和信息安全"
theme = "easybook"

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

paginate = 8                                              # 首页每页显示的文章数
googleAnalytics = "UA-131218098-1"      # UA-XXXXXXXX-X
# 右上角菜单
[[menu.main]]
  name = "Home"
  weight = 10
  url = "/"
[[menu.main]]
  name = "Category"
  weight = 20
  url = "/post/"
[[menu.main]]
  name = "Daily"
  weight = 30
  url = "/words"
[[menu.main]]
  name = "About"
  weight = 40
  url = "/about"
[[menu.main]]
  name = "T00ls"
  weight = 50
  url = "https://www.t00ls.net/members-profile-12869.html"

# 站点信息
[params]
  author = "Mature"
  whoami = "一名信息安全爱好者!"
  avatar = "https://ae01.alicdn.com/kf/U4076cc26dcb1472abae912383cae82d12.jpg"
  keywords = ["Mature","信息安全","网络安全","红蓝攻防","渗透测试","bypass","waf","注入","黑客","chabug"]
  description = "伪程序员,信安爱好者,专注于网络攻防和信息安全."

  [params.social]
    GitHub = "https://github.com/aping001"
    Email = "mailto:admin@chabug.org"
  [params.utterances]       # https://utteranc.es/
    owner = "Mature"              # Your GitHub ID
    repo = "ninjia.org"               # The repo to store comments
  baiduPush = true        # baidu push                  # 百度
  baiduAnalytics = "150ef5faf0461b9f83612d60d72b86b1"      # Baidu Analytics
  baiduVerification = "PsCl6huhUk"   # Baidu Verification
  googleVerification = "gPHyyln9EbiXF7wv-nBpX50vJcwJbi1KKbUyFOxuVkA"  # Google Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []
